use std::path::PathBuf;
use anyhow::{Result, Context};
use boil_core::canon::state::CanonState;
use crate::batch::distillation::{DistillationConfig, Target, distill_canon};

pub fn build_globset(patterns: &[String]) -> globset::GlobSet {
    let mut builder = globset::GlobSetBuilder::new();
    for p in patterns {
        if let Ok(glob) = globset::Glob::new(p) {
            builder.add(glob);
        }
    }
    builder.build().unwrap_or_else(|_| globset::GlobSet::empty())
}

pub fn run_distill(
    repo: PathBuf,
    output: PathBuf,
    canon_path: Option<PathBuf>,
    focus: Option<Vec<String>>,
    target: Option<String>,
    embedding_provider: String,
) -> Result<()> {
    let mut state = match &canon_path {
        Some(path) => {
            println!("Loading binary canon from {}...", path.display());
            CanonState::load(path)
                .context("Failed to load binary canon. Make sure it was generated by `boil canon`")?
        }
        None => {
            println!("No canon file provided. Generating index on-the-fly...");
            boil_engine::indexer::generate_canon_state(&repo)
                .context("Failed to generate in-memory project index")?
        }
    };

    let parsed_target = target.and_then(|t| {
        if t.ends_with('%') {
            t.trim_end_matches('%').parse::<f64>().ok().map(Target::Percent)
        } else if t.ends_with('b') || t.ends_with('B') {
            t[..t.len()-1].parse::<usize>().ok().map(Target::Bytes)
        } else {
            None
        }
    });

    let config = DistillationConfig {
        raw: build_globset(&[]),
        focus: build_globset(&focus.unwrap_or_default()),
        target: parsed_target,
        force_timestamp: None,
        silent: false,
        embedding_provider,
    };

    println!("Distilling canon...");
    let dummy_path = canon_path.clone().unwrap_or_else(|| PathBuf::from(""));
    distill_canon(
        &repo,
        &output,
        &dummy_path,
        &config,
        &mut state.file_infos,
        &mut state.graph
    )?;

    Ok(())
}
